services:
# ===============================================================
#   Building Ubuntu Base Image 
# ===============================================================
  ubuntu20.04:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:20.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu20.04

  ubuntu20.04-dind:
    build:
      context: .
      args:
        BASE_IMAGE: cruizba/ubuntu-dind:focal-26.0.1
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/dind-base:ubuntu20.04

  ubuntu20.04-cuda11.7:
    build:
      context: .
      args:
        BASE_IMAGE: nvidia/cuda:11.7.1-devel-ubuntu20.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7

  ubuntu20.04-nvidia-egl:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/selkies-project/nvidia-egl-desktop:20.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/nvidia-egl:ubuntu20.04-cuda11.0

  ubuntu22.04:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:22.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu22.04

  ubuntu22.04-dind:
    build:
      context: .
      args:
        BASE_IMAGE: cruizba/ubuntu-dind:jammy-26.0.1
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/dind-base:ubuntu22.04

  ubuntu22.04-cuda11.7:
    build:
      context: .
      args:
        BASE_IMAGE: nvidia/cuda:11.7.1-devel-ubuntu22.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu22.04-cuda11.7

  ubuntu22.04-nvidia-egl:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/selkies-project/nvidia-egl-desktop:22.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/nvidia-egl:ubuntu22.04-cuda11.0

  ubuntu24.04:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:24.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu24.04

  ubuntu24.04-dind:
    build:
      context: .
      args:
        BASE_IMAGE: cruizba/ubuntu-dind:noble-26.0.1
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/dind-base:ubuntu24.04

# ===============================================================
#   Building ROS1 Base Image
# ===============================================================
  ubuntu20.04-noetic:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04
        ROS_DISTRO: noetic
      dockerfile: dockerfiles/Dockerfile.ros1
    depends_on: 
      - ubuntu20.04
    image: ghcr.io/shunmo17/ros1:noetic

  ubuntu20.04-cuda11.7-noetic:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7
        ROS_DISTRO: noetic
      dockerfile: dockerfiles/Dockerfile.ros1
    depends_on: 
      - ubuntu20.04-cuda11.7
    image: ghcr.io/shunmo17/ros1:noetic-cuda11.7

  ubuntu20.04-nvidia-egl-noetic:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/nvidia-egl:ubuntu20.04-cuda11.0
        ROS_DISTRO: noetic
      dockerfile: dockerfiles/Dockerfile.ros1
    depends_on: 
      - ubuntu20.04-nvidia-egl
    image: ghcr.io/shunmo17/ros1:noetic-nvidia-egl-cuda11.0

# ===============================================================
#   Building ROS2 Base Image
# ===============================================================
  ubuntu22.04-humble:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu22.04
        ROS_DISTRO: humble
      dockerfile: dockerfiles/Dockerfile.ros2
    depends_on: 
      - ubuntu22.04
    image: ghcr.io/shunmo17/ros2:humble

  ubuntu22.04-cuda11.7-humble:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu22.04-cuda11.7
        ROS_DISTRO: humble
      dockerfile: dockerfiles/Dockerfile.ros2
    depends_on: 
      - ubuntu22.04-cuda11.7
    image: ghcr.io/shunmo17/ros2:humble-cuda11.7

  ubuntu22.04-nvidia-egl-humble:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/nvidia-egl:ubuntu22.04-cuda11.0
        ROS_DISTRO: humble
      dockerfile: dockerfiles/Dockerfile.ros2
    depends_on: 
      - ubuntu22.04-nvidia-egl
    image: ghcr.io/shunmo17/ros2:humble-nvidia-egl-cuda11.0
