services:
  # ===============================================================
  #   Building Ubuntu Desktop Base Image with NVIDIA-EGL-Desktop
  # ===============================================================
  # ubuntu 24.04 -------------------------------------------------
  ubuntu24.04-desktop:
    build:
      context: docker-nvidia-egl-desktop
      args:
        BASE_IMAGE: ubuntu:24.04
        PASSWD: user
      dockerfile: Dockerfile
    image: ghcr.io/shunmo17/nvidia-egl-desktop:ubuntu24.04

  # ===============================================================
  #   Building Ubuntu Base Image 
  # ===============================================================
  # ubuntu 24.04 -------------------------------------------------
  ubuntu24.04:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:24.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu24.04

  ubuntu24.04-dind:
    build:
      context: .
      args:
        BASE_IMAGE: cruizba/ubuntu-dind:noble-latest
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/dind-base:ubuntu24.04

  # ubuntu 26.04 -------------------------------------------------
  ubuntu26.04:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:26.04
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu26.04

  ubuntu26.04-dind:
    build:
      context: .
      args:
        BASE_IMAGE: cruizba/ubuntu-dind:resolute-latest
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/dind-base:ubuntu26.04
