version: "2.3"
services:
# ===============================================================
#   Building Ubuntu Base Image 
# ===============================================================
  ubuntu20:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:20.04
        PASSWD: user
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu20.04

  ubuntu20_cuda117:
    build:
      context: .
      args:
        BASE_IMAGE: nvidia/cuda:11.7.1-devel-ubuntu20.04
        PASSWD: user
      dockerfile: dockerfiles/Dockerfile.base
    image: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7

# ===============================================================
#   Add PyTorch
# ===============================================================
  ubuntu20_cuda117_pytorch200:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7
      dockerfile: dockerfiles/Dockerfile.pytorch
    depends_on:
      - ubuntu20_cuda117
    image: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7-pytorch2.0.0

# ===============================================================
#   Building ROS1 Base Image
# ===============================================================
  ubuntu20_noetic:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04
        ROS_DISTRO: noetic
      dockerfile: dockerfiles/Dockerfile.ros1
    depends_on: 
      - ubuntu20
    image: ghcr.io/shunmo17/ros1:noetic

  ubuntu20_cuda117_noetic:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7
        ROS_DISTRO: noetic
      dockerfile: dockerfiles/Dockerfile.ros1
    depends_on: 
      - ubuntu20_cuda117
    image: ghcr.io/shunmo17/ros1:noetic-cuda11.7

  ubuntu20_cuda117_pytorch200_noetic:
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7-pytorch2.0.0
        ROS_DISTRO: noetic
      dockerfile: dockerfiles/Dockerfile.ros1
    depends_on: 
      - ubuntu20_cuda117_pytorch200
    image: ghcr.io/shunmo17/ros1:noetic-cuda11.7-pytorch2.0.0

# # ===============================================================
# #   Add ROS2
# # ===============================================================
#   ubuntu20_foxy:
#     build:
#       context: .
#       args:
#         BASE_IMAGE: ghcr.io/shunmo17/ubuntu:20.04
#         ROS_DISTRO: foxy
#       dockerfile: dockerfiles/Dockerfile.ros2
#     depends_on: 
#       - ubuntu20
#     image: ghcr.io/shunmo17/ros2:foxy

#   ubuntu20_cuda117_foxy:
#     build:
#       context: .
#       args:
#         BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7
#         ROS_DISTRO: foxy
#       dockerfile: dockerfiles/Dockerfile.ros1
#     depends_on: 
#       - ubuntu20_cuda117
#     image: ghcr.io/shunmo17/ros2:foxy-cuda11.7

#   ubuntu20_cuda117_pytorch200_foxy:
#     build:
#       context: .
#       args:
#         BASE_IMAGE: ghcr.io/shunmo17/base:ubuntu20.04-cuda11.7-pytorch2.0.0
#         ROS_DISTRO: foxy
#       dockerfile: dockerfiles/Dockerfile.ros1
#     depends_on: 
#       - ubuntu20_cuda117_pytorch200
#     image: ghcr.io/shunmo17/ros2:foxy-cuda11.7-pytorch2.0.0
