services:
  ubuntu24.04-desktop:
    extends:
      file: docker-compose.common.yml
      service: nvidia-edl-desktop

  ubuntu24.04:
    extends:
      file: docker-compose.common.yml
      service: normal

  ubuntu24.04-dind:
    extends:
      file: docker-compose.common.yml
      service: normal

  ubuntu26.04:
    extends:
      file: docker-compose.common.yml
      service: normal

  ubuntu26.04-dind:
    extends:
      file: docker-compose.common.yml
      service: normal
