ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt update && apt install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install torch==2.0.0+cu117 -f https://download.pytorch.org/whl/torch_stable.html
