name: Build and Publish Docker

on:
  push:
    branches:
      - master
      - devel

jobs:
  build_and_push_ubuntu16:
    runs-on: ubuntu-latest
    env:
      UBUNTU: 16
      IMAGE_NAME: ubuntu${{ env.UBUNTU }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:1.0.0
          build_extra_args: "--build-arg=BASE_IMAGE=ubuntu:${{ env.UBUNTU }}.04 --build-arg=UBUNTU=${{ env.UBUNTU }}"
  
  build_and_push_ubuntu18:
    runs-on: ubuntu-latest
    env:
      UBUNTU: 18
      IMAGE_NAME: ubuntu${{ env.UBUNTU }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:1.0.0
          build_extra_args: "--build-arg=BASE_IMAGE=ubuntu:${{ env.UBUNTU }}.04 --build-arg=UBUNTU=${{ env.UBUNTU }}"
  
  build_and_push_ubuntu20:
    runs-on: ubuntu-latest
    env:
      UBUNTU: 20
      IMAGE_NAME: ubuntu${{ env.UBUNTU }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:1.0.0
          build_extra_args: "--build-arg=BASE_IMAGE=ubuntu:${{ env.UBUNTU }}.04 --build-arg=UBUNTU=${{ env.UBUNTU }}"
