name: Build ROS2 Base

on:
  push:
    branches:
      - master
      - devel

jobs:
  build_ros2_dashing_without_nvidia:
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: dashing
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          tag_with_ref: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu
          push: true
          tags: |
            ghcr.io/shunmo17/ros2:${{ env.ROS_DISTRO }}
          build-args: |
            BASE_IMAGE=ghcr.io/shunmo17/ubuntu:18.04
            ROS_DISTRO=${{ env.ROS_DISTRO }}
          file: ./ros2/Dockerfile

  build_ros2_dashing_with_nvidia:
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: dashing
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          tag_with_ref: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu
          push: true
          tags: |
            ghcr.io/shunmo17/ros2.nvidia:${{ env.ROS_DISTRO }}
          build-args: |
            BASE_IMAGE=ghcr.io/shunmo17/ubuntu.nvidia:18.04
            ROS_DISTRO=${{ env.ROS_DISTRO }}
          file: ./ros2/Dockerfile
