name: Build Base Images

on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          temp-reserve-m: 1024
          remove-dotnet: "true"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # - name: Setup buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build images
      #   run: docker buildx bake --file docker-compose.yml --file .github/docker-compose-cache.json

      - name: Build images
        run: docker compose build

      - name: Push images
        run: docker compose push
