name: Clean Container Registry
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          temp-reserve-m: 1024
          remove-dotnet: "true"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: docker buildx bake --file docker-compose.yml --file .github/docker-compose-cache.json

      - name: Push images
        run: docker compose push

  delete_untagged:
    name: Delete Untagged Packages
    runs-on: ubuntu-latest

    steps:
      - name: Delete Untagged Packages
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
